name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Asegúrate de que esta versión coincida con la de tu proyecto

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-artifact
        path: publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: backend-artifact

    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        # Aquí irían los comandos para desplegar a tu entorno de staging
        # Por ejemplo, podrías usar Azure CLI para desplegar a Azure App Service:
        # az webapp deployment source config-zip --resource-group myResourceGroup --name myAppName --src backend-artifact.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false